modLoader="javafml"
loaderVersion="[38,)"
license="BSD (3 clause)"

[[mods]]
modId="enderrift"
version="${file.jarVersion}"
updateJSONURL="https://raw.githubusercontent.com/gigaherz/Ender-Rift/master/update.json"
displayName="Ender-Rift"
description='''
Bottomless Powered Inventory
'''
issueTrackerURL="https://github.com/gigaherz/Ender-Rift/issues"
displayURL="https://github.com/gigaherz/Ender-Rift"
logoFile="logo.png"
credits="Thanks for this example mod goes to Java"
authors="gigaherz"

[[dependencies.enderrift]]
   modId="forge"
   mandatory=true
   versionRange="[38.0.16,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.enderrift]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.18,1.19)"
   ordering="NONE"
   side="BOTH"
[[dependencies.enderrift]]
   modId="waila"
   mandatory=false
   versionRange="[0,)"
   ordering="AFTER"
   side="BOTH"