modLoader="javafml"
loaderVersion="[41,)"
license="BSD (3 clause)"
issueTrackerURL="https://github.com/gigaherz/Ender-Rift/issues"

[[mods]]
modId="enderrift"
version="${file.jarVersion}"
updateJSONURL="https://raw.githubusercontent.com/gigaherz/Ender-Rift/master/update.json"
displayName="Ender-Rift"
description='''
Bottomless Powered Inventory
'''
displayURL="https://github.com/gigaherz/Ender-Rift"
logoFile="logo.png"
authors="gigaherz"

[[dependencies.enderrift]]
   modId="forge"
   mandatory=true
   versionRange="[41.0.17,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.enderrift]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.19,1.20)"
   ordering="NONE"
   side="BOTH"
[[dependencies.enderrift]]
   modId="waila"
   mandatory=false
   versionRange="[0,)"
   ordering="AFTER"
   side="BOTH"