modLoader="javafml"
loaderVersion="[25,)"
#updateJSONURL="http://myurl.me/"
issueTrackerURL="https://github.com/gigaherz/Ender-Rift/issues"
displayURL="https://github.com/gigaherz/Ender-Rift"
logoFile="logo.png"
credits="Thanks for this example mod goes to Java"
authors="gigaherz"

[[mods]]
modId="enderrift"
version="${version}"
displayName="Ender-Rift"
description='''
Bottomless Powered Inventory
'''

[[dependencies.toolbelt]]
   modId="forge"
   mandatory=true
   versionRange="[26.0.12,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.toolbelt]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.14.2,1.15)"
   ordering="NONE"
   side="BOTH"